### YamlMime:ManagedReference
items:
- uid: NGOExtraSettings.ExtraSettings
  commentId: T:NGOExtraSettings.ExtraSettings
  id: ExtraSettings
  parent: NGOExtraSettings
  children:
  - NGOExtraSettings.ExtraSettings.#ctor
  - NGOExtraSettings.ExtraSettings.LoadFromExtSettings``1(System.String)
  - NGOExtraSettings.ExtraSettings.SaveToExtSettings``1(System.String,``0)
  langs:
  - csharp
  - vb
  name: ExtraSettings
  nameWithType: ExtraSettings
  fullName: NGOExtraSettings.ExtraSettings
  type: Class
  assemblies:
  - NGOExtraSettings
  namespace: NGOExtraSettings
  syntax:
    content: public class ExtraSettings
    content.vb: Public Class ExtraSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: NGOExtraSettings.ExtraSettings.LoadFromExtSettings``1(System.String)
  commentId: M:NGOExtraSettings.ExtraSettings.LoadFromExtSettings``1(System.String)
  id: LoadFromExtSettings``1(System.String)
  parent: NGOExtraSettings.ExtraSettings
  langs:
  - csharp
  - vb
  name: LoadFromExtSettings<T>(string)
  nameWithType: ExtraSettings.LoadFromExtSettings<T>(string)
  fullName: NGOExtraSettings.ExtraSettings.LoadFromExtSettings<T>(string)
  type: Method
  assemblies:
  - NGOExtraSettings
  namespace: NGOExtraSettings
  syntax:
    content: public static T LoadFromExtSettings<T>(string key)
    parameters:
    - id: key
      type: System.String
    typeParameters:
    - id: T
    return:
      type: '{T}'
    content.vb: Public Shared Function LoadFromExtSettings(Of T)(key As String) As T
  overload: NGOExtraSettings.ExtraSettings.LoadFromExtSettings*
  nameWithType.vb: ExtraSettings.LoadFromExtSettings(Of T)(String)
  fullName.vb: NGOExtraSettings.ExtraSettings.LoadFromExtSettings(Of T)(String)
  name.vb: LoadFromExtSettings(Of T)(String)
- uid: NGOExtraSettings.ExtraSettings.SaveToExtSettings``1(System.String,``0)
  commentId: M:NGOExtraSettings.ExtraSettings.SaveToExtSettings``1(System.String,``0)
  id: SaveToExtSettings``1(System.String,``0)
  parent: NGOExtraSettings.ExtraSettings
  langs:
  - csharp
  - vb
  name: SaveToExtSettings<T>(string, T)
  nameWithType: ExtraSettings.SaveToExtSettings<T>(string, T)
  fullName: NGOExtraSettings.ExtraSettings.SaveToExtSettings<T>(string, T)
  type: Method
  assemblies:
  - NGOExtraSettings
  namespace: NGOExtraSettings
  syntax:
    content: public static void SaveToExtSettings<T>(string key, T data)
    parameters:
    - id: key
      type: System.String
    - id: data
      type: '{T}'
    typeParameters:
    - id: T
    content.vb: Public Shared Sub SaveToExtSettings(Of T)(key As String, data As T)
  overload: NGOExtraSettings.ExtraSettings.SaveToExtSettings*
  nameWithType.vb: ExtraSettings.SaveToExtSettings(Of T)(String, T)
  fullName.vb: NGOExtraSettings.ExtraSettings.SaveToExtSettings(Of T)(String, T)
  name.vb: SaveToExtSettings(Of T)(String, T)
- uid: NGOExtraSettings.ExtraSettings.#ctor
  commentId: M:NGOExtraSettings.ExtraSettings.#ctor
  id: '#ctor'
  parent: NGOExtraSettings.ExtraSettings
  langs:
  - csharp
  - vb
  name: ExtraSettings()
  nameWithType: ExtraSettings.ExtraSettings()
  fullName: NGOExtraSettings.ExtraSettings.ExtraSettings()
  type: Constructor
  assemblies:
  - NGOExtraSettings
  namespace: NGOExtraSettings
  syntax:
    content: public ExtraSettings()
    content.vb: Public Sub New()
  overload: NGOExtraSettings.ExtraSettings.#ctor*
  nameWithType.vb: ExtraSettings.New()
  fullName.vb: NGOExtraSettings.ExtraSettings.New()
  name.vb: New()
references:
- uid: NGOExtraSettings
  commentId: N:NGOExtraSettings
  isExternal: true
  href: NGOExtraSettings.html
  name: NGOExtraSettings
  nameWithType: NGOExtraSettings
  fullName: NGOExtraSettings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NGOExtraSettings.ExtraSettings.LoadFromExtSettings*
  commentId: Overload:NGOExtraSettings.ExtraSettings.LoadFromExtSettings
  isExternal: true
  href: NGOExtraSettings.ExtraSettings.html#NGOExtraSettings_ExtraSettings_LoadFromExtSettings__1_System_String_
  name: LoadFromExtSettings
  nameWithType: ExtraSettings.LoadFromExtSettings
  fullName: NGOExtraSettings.ExtraSettings.LoadFromExtSettings
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: NGOExtraSettings.ExtraSettings.SaveToExtSettings*
  commentId: Overload:NGOExtraSettings.ExtraSettings.SaveToExtSettings
  isExternal: true
  href: NGOExtraSettings.ExtraSettings.html#NGOExtraSettings_ExtraSettings_SaveToExtSettings__1_System_String___0_
  name: SaveToExtSettings
  nameWithType: ExtraSettings.SaveToExtSettings
  fullName: NGOExtraSettings.ExtraSettings.SaveToExtSettings
- uid: NGOExtraSettings.ExtraSettings.#ctor*
  commentId: Overload:NGOExtraSettings.ExtraSettings.#ctor
  isExternal: true
  href: NGOExtraSettings.ExtraSettings.html#NGOExtraSettings_ExtraSettings__ctor
  name: ExtraSettings
  nameWithType: ExtraSettings.ExtraSettings
  fullName: NGOExtraSettings.ExtraSettings.ExtraSettings
  nameWithType.vb: ExtraSettings.New
  fullName.vb: NGOExtraSettings.ExtraSettings.New
  name.vb: New
