### YamlMime:ManagedReference
items:
- uid: NGOExtraSettings
  commentId: N:NGOExtraSettings
  id: NGOExtraSettings
  children:
  - NGOExtraSettings.ExtraSettings
  langs:
  - csharp
  - vb
  name: NGOExtraSettings
  nameWithType: NGOExtraSettings
  fullName: NGOExtraSettings
  type: Namespace
  assemblies:
  - NGOExtraSettings
references:
- uid: NGOExtraSettings.ExtraSettings
  commentId: T:NGOExtraSettings.ExtraSettings
  isExternal: true
  href: NGOExtraSettings.ExtraSettings.html
  name: ExtraSettings
  nameWithType: ExtraSettings
  fullName: NGOExtraSettings.ExtraSettings
